pipeline:
  name: 建木文档CI/CD
  ref: jianmu_docs_cicd
  description: 建木文档CI/CD
  git_clone:
    type: git:v1.0
    param:
      workspace: jianmu-docs
      remote_url: https://gitee.com/jianmu_dev/jianmu-docs.git
      commit_branch: master
      netrc_machine: gitee.com
      netrc_username: ((gitee.username))
      netrc_password: ((gitee.password))
  node_build:
    type: node_build:14.16.1-alpine3.13-result
    param:
      workspace: jianmu-docs
  update_resoure:
    type: ssh_update:v1.0
    param:
      ssh_private_key: ((private_key.alixg))
      ssh_host: root@47.243.164.48
      remote_file: /etc/nginx/docs
      local_file: jianmu-docs/.vitepress/dist
  send_message:
    type: qywx_notice:v1.0
    param:
      bot_webhook_url: ((charbot.webhook_url))
      mentioned_moblie_list: "[]"
      text_content: "建木文档更新完成"
      msgtype: "text"
      mentioned_list: "[]"
